# Generated by Django 5.2.16 on 2026-07-14 22:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_video_uuids(apps, schema_editor):
    Video = apps.get_model('api', 'Video')
    seen = set()
    for video in Video.objects.all().order_by('id'):
        if video.uuid is None or video.uuid in seen:
            video.uuid = uuid.uuid4()
        while video.uuid in seen:
            video.uuid = uuid.uuid4()
        seen.add(video.uuid)
        video.save(update_fields=['uuid'])

def backfill_webcamrecording_uuids(apps, schema_editor):
    WebcamRecording = apps.get_model('api', 'WebcamRecording')
    seen = set()
    for rec in WebcamRecording.objects.all().order_by('id'):
        if rec.uuid is None or rec.uuid in seen:
            rec.uuid = uuid.uuid4()
        while rec.uuid in seen:
            rec.uuid = uuid.uuid4()
        seen.add(rec.uuid)
        rec.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_thumbnail_url_to_webcamrecording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.AddField(
            model_name='video',
            name='duration_seconds',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='webcamrecording',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emotionframe',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_frame_viewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], db_index=True, default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='webcamrecording',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='webcamrecording',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcam_recordings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webcamrecording',
            name='recording_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='webcamrecording',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='analysisrunlog',
            index=models.Index(fields=['-started_at'], name='api_analysi_started_c99f89_idx'),
        ),
        migrations.AddIndex(
            model_name='emotionframe',
            index=models.Index(fields=['video', 'viewer'], name='api_emotion_video_i_17f51a_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['visibility', 'auto_private_after'], name='videos_visibil_26ce5a_idx'),
        ),
        migrations.AddIndex(
            model_name='webcamrecording',
            index=models.Index(fields=['upload_status', 'analysis_status'], name='api_webcamr_upload__475976_idx'),
        ),
        migrations.AddIndex(
            model_name='webcamrecording',
            index=models.Index(fields=['recorder', '-recording_date'], name='api_webcamr_recorde_da7f5e_idx'),
        ),
        migrations.RunPython(backfill_video_uuids, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(backfill_webcamrecording_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='webcamrecording',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
