# Generated by Django 5.2.16 on 2026-07-15 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('star_rating', 'Star Rating'), ('emoji_rating', 'Emoji Rating'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkbox'), ('text', 'Text')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.CharField(default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'survey_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(default=dict)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_bug_report', models.BooleanField(default=False)),
                ('consent_to_improve', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('post_analysis', 'Post Analysis'), ('manual', 'Manual')], default='post_analysis', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to='api.video')),
            ],
            options={
                'db_table': 'feedback_responses',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'video'], name='feedback_re_user_id_13975f_idx'), models.Index(fields=['-submitted_at'], name='feedback_re_submitt_b353aa_idx')],
            },
        ),
    ]
