# Generated by Django 5.2.16 on 2026-07-15 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_feedback_survey_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('video_liked', 'Video Liked'), ('webcam_upload_complete', 'Webcam Upload Complete'), ('recording_analyzed', 'Recording Analyzed'), ('analysis_run_completed', 'Analysis Run Completed'), ('points_earned', 'Points Earned'), ('video_view_limit_reached', 'View Limit Reached'), ('video_auto_privated', 'Video Auto-Privated'), ('user_promoted', 'User Promoted to Admin'), ('new_user_registered', 'New User Registered'), ('system_announcement', 'System Announcement'), ('upload_request_submitted', 'Upload Request Submitted'), ('upload_request_approved', 'Upload Request Approved'), ('upload_request_rejected', 'Upload Request Rejected'), ('upload_request_processing', 'Upload Request Processing'), ('upload_request_completed', 'Upload Request Completed'), ('upload_request_cancelled', 'Upload Request Cancelled'), ('upload_request_comment', 'Upload Request Comment')], max_length=50),
        ),
        migrations.CreateModel(
            name='UploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_request', to='api.video')),
            ],
            options={
                'verbose_name': 'Upload Request',
                'verbose_name_plural': 'Upload Requests',
                'db_table': 'upload_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadRequestStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('upload_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='api.uploadrequest')),
            ],
            options={
                'verbose_name': 'Upload Request Status Log',
                'verbose_name_plural': 'Upload Request Status Logs',
                'db_table': 'upload_request_status_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadrequest',
            index=models.Index(fields=['company', 'status'], name='upload_requ_company_f8d2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadrequest',
            index=models.Index(fields=['status', '-created_at'], name='upload_requ_status_b9b27b_idx'),
        ),
    ]
