# Generated by Django 5.2.16 on 2026-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_upload_request_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcamrecording',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
