# Generated by Django 5.2.16 on 2026-07-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_points_awarded_to_webcamrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('video_liked', 'Video Liked'), ('webcam_upload_complete', 'Webcam Upload Complete'), ('recording_analyzed', 'Recording Analyzed'), ('analysis_run_completed', 'Analysis Run Completed'), ('points_earned', 'Points Earned'), ('video_view_limit_reached', 'View Limit Reached'), ('video_auto_privated', 'Video Auto-Privated'), ('user_promoted', 'User Promoted to Admin'), ('new_user_registered', 'New User Registered'), ('system_announcement', 'System Announcement'), ('upload_request_submitted', 'Upload Request Submitted'), ('upload_request_approved', 'Upload Request Approved'), ('upload_request_rejected', 'Upload Request Rejected'), ('upload_request_processing', 'Upload Request Processing'), ('upload_request_completed', 'Upload Request Completed'), ('upload_request_cancelled', 'Upload Request Cancelled'), ('upload_request_comment', 'Upload Request Comment'), ('feedback_submitted', 'Feedback Submitted')], max_length=50),
        ),
    ]
