# Generated by Django 5.2.16 on 2026-07-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_feedback_submitted_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
