# Generated by Django 5.2.16 on 2026-07-20 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_liveness_fields_to_webcamrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('user', 'User')], db_index=True, default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='videolike',
            index=models.Index(fields=['user', '-liked_at'], name='video_likes_user_id_ebffbc_idx'),
        ),
        migrations.AddIndex(
            model_name='videoview',
            index=models.Index(fields=['viewer', '-viewed_at'], name='video_views_viewer__ca55c6_idx'),
        ),
        migrations.AddIndex(
            model_name='webcamrecording',
            index=models.Index(fields=['video', 'upload_status'], name='api_webcamr_video_i_56135b_idx'),
        ),
    ]
