# Generated by Django 5.2.16 on 2026-07-20 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedbackresponse',
            name='feedback_re_user_id_13975f_idx',
        ),
        migrations.RemoveIndex(
            model_name='videoview',
            name='video_views_video_i_45fbf8_idx',
        ),
        migrations.AlterField(
            model_name='emotionframe',
            name='confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='emotionframe',
            name='t_seconds',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='webcamrecording',
            name='liveness_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackresponse',
            unique_together={('user', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='videoview',
            unique_together={('video', 'viewer')},
        ),
    ]
